#!/usr/bin/env fish
# Launch a Claude Code Agent Teams session for vestaboard-ai-haiku inside tmux.
# Generated by agent-teams-scaffold. Requires Claude Code v2.1.32+ (teams) and tmux 3.2+ (split panes).

set -l script_dir (dirname (status -f))
set -l repo_dir (realpath "$script_dir/..")
set -l session vestaboard-ai-haiku

cd "$repo_dir"; or exit 1

# Enable the experimental Agent Teams feature for this process tree.
set -x CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS 1

if not type -q claude
    echo "claude CLI not found on PATH." >&2
    exit 127
end

if not type -q tmux
    echo "tmux not found — launching Claude in-process (no split panes)."
    exec claude
end

if tmux has-session -t $session 2>/dev/null
    echo "Attaching to existing tmux session '$session'."
    exec tmux attach -t $session
else
    echo "Starting tmux session '$session' with Agent Teams enabled."
    # -e injects the env var into the whole tmux session (tmux 3.2+).
    exec tmux new-session -s $session -e CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS=1 claude
end
